[project]
name = "switchbot-prometheus-exporter"
version = "0.0.1"
description = "Prometheus exporter for SwitchBot meter"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bleak>=0.22.3",
    "click>=8.2.0",
    "prometheus-client>=0.21.1",
]
